# Generated by Django 5.0.1 on 2024-02-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('tres_mauvais', 'Très mauvais'), ('mauvais', 'Mauvais'), ('moyen', 'Moyen'), ('bon', 'Bon'), ('excellent', 'Excellent')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
