# Generated by Django 5.0.1 on 2024-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_delete_satisfaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='emoji',
            field=models.CharField(choices=[('very bad', -2), ('bad', -1), ('happy', 1), ('very happy', 2)], default='happy', max_length=10),
        ),
    ]
